name: Build and deploy static site to GitHub Pages

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Debug: show runner info and repo files
        run: |
          echo "--- Python ---"
          python --version || true
          echo "--- Files in repo root ---"
          ls -la
          echo "--- requirements.txt (head) ---"
          if [ -f requirements.txt ]; then head -n 50 requirements.txt; fi
          echo "--- pip freeze ---"
          python -m pip freeze || true

      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run migrations and populate DB
        run: |
          python manage.py migrate --noinput || true
          python manage.py populate_roadmap || true

      - name: Build static site
        run: python tools/build_static.py

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./roadmap
